[workspace]
members = ["retract_fsm_transition"]

[workspace.package]
authors = ["Cameron Rodriguez <dev@camrod.me>"]

[package]
name = "aps490_retraction_fsm"
version = "0.1.0"
authors.workspace = true
description = "FSM for saw MCU"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retract_fsm_transition = { path = "retract_fsm_transition" }