[package]
name = "aps490_retraction_fsm"
version = "0.1.0"
authors = ["Cameron Rodriguez <dev@camord.me>"]
description = "FSM for saw MCU"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
